In [1]:
! pip install -r requirment.txt

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import  seaborn as sns
%matplotlib inline

In [3]:
df=sns.load_dataset("tips")

In [4]:
df

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   total_bill  244 non-null    float64 
 1   tip         244 non-null    float64 
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64   
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB


In [6]:
df["sex"].unique()


['Female', 'Male']
Categories (2, object): ['Male', 'Female']

In [7]:
df["smoker"].unique()


['No', 'Yes']
Categories (2, object): ['Yes', 'No']

In [8]:
df["day"].unique()


['Sun', 'Sat', 'Thur', 'Fri']
Categories (4, object): ['Thur', 'Fri', 'Sat', 'Sun']

In [9]:
df["time"].unique()


['Dinner', 'Lunch']
Categories (2, object): ['Lunch', 'Dinner']

In [10]:
df["size"].unique()


array([2, 3, 4, 1, 6, 5])

In [11]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

## we will be predicting smoker on the basis of time,day,sex

In [12]:
X=df[['sex','day','time']]
y=df['smoker']

In [13]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25)

## Feature Encoding

In [ ]:
from sklearn.preprocessing import LabelEncoder
le1=LabelEncoder()
le2=LabelEncoder()
le3=LabelEncoder()
X_train['sex']=le1.fit_transform(X_train['sex'])
X_train['time']=le3.fit_transform(X_train['time'])

In [15]:
X_train.head()

sex  day  time
156    1    2     0
217    1    1     0
8      1    2     0
162    0    2     0
55     1    2     0

In [16]:
X_train['day'].unique()

array([2, 1, 3, 0])

In [ ]:
X_test['sex']=le1.fit_transform(X_test['sex'])
X_test['time']=le3.fit_transform(X_test['time'])

In [19]:
## Applying one hotencoding for day
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct=ColumnTransformer(transformers=[('onehot',OneHotEncoder(drop='first'),[1])],remainder='passthrough')


In [20]:
X_train=ct.fit_transform(X_train)
X_test=ct.fit_transform(X_test)

## Applying naive bayes theorm

In [22]:
from sklearn.naive_bayes import GaussianNB, CategoricalNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# ------------------ GaussianNB ------------------
gnb = GaussianNB()
gnb.fit(X_train, y_train)
y_pred_gnb = gnb.predict(X_test)

print("🔹 GaussianNB Results")
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_gnb))
print("Accuracy:", accuracy_score(y_test, y_pred_gnb))
print("Classification Report:\n", classification_report(y_test, y_pred_gnb))

print("\n" + "="*60 + "\n")

# ------------------ CategoricalNB ------------------
cnb = CategoricalNB()
cnb.fit(X_train, y_train)
y_pred_cnb = cnb.predict(X_test)

print("🔹 CategoricalNB Results")
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_cnb))
print("Accuracy:", accuracy_score(y_test, y_pred_cnb))
print("Classification Report:\n", classification_report(y_test, y_pred_cnb))



🔹 GaussianNB Results
Confusion Matrix:
 [[35 11]
 [11  4]]
Accuracy: 0.639344262295082
Classification Report:
               precision    recall  f1-score   support

          No       0.76      0.76      0.76        46
         Yes       0.27      0.27      0.27        15

    accuracy                           0.64        61
   macro avg       0.51      0.51      0.51        61
weighted avg       0.64      0.64      0.64        61



🔹 CategoricalNB Results
Confusion Matrix:
 [[36 10]
 [12  3]]
Accuracy: 0.639344262295082
Classification Report:
               precision    recall  f1-score   support

          No       0.75      0.78      0.77        46
         Yes       0.23      0.20      0.21        15

    accuracy                           0.64        61
   macro avg       0.49      0.49      0.49        61
weighted avg       0.62      0.64      0.63        61

